### PR TITLE
added mocked tests for databases - part 4

### PR DESCRIPTION
**Pull request by work-mohit**
Refer Issue : #207

Add tests for `databases.patch_config`, `databases.reset_auth`, `databases.update_cluster_size`, `databases.update_firewall_rules`, `databases.update_maintenance_window`, `databases.online_migration`, `databases.update_region`, `databases.update_sql_mode`

for `databases.promote_replica`, `databases.update_connection_pool`,
`databases.update_major_version` tests were already there.

### CODE REVIEW

**Review by danaelhe — CHANGES_REQUESTED** [review]
Awesome work!! Just need to run `poetry run black tests` and push up the changes to resolve the lint failures 👍

**Comment by work-mohit** [comment]
have a look at this PR, I guess this is ready to merge!

**Comment by danaelhe** [comment]
The lint failure can be ignored. Add `# pylint: disable=too-many-lines` at the top of your file.

**Comment by work-mohit** [comment]
The pushed branch have `# pylint: disable=too-many-lines` at the top but still failing lint tests

**Comment by danaelhe** [comment]
> The pushed branch have `# pylint: disable=too-many-lines` at the top but still failing lint tests

it currently has `# pylint: disable=line-too-long`, you'll need to add `# pylint: disable=too-many-lines`. They're very similar 😆

**Comment by work-mohit** [comment]
> > The pushed branch have `# pylint: disable=too-many-lines` at the top but still failing lint tests
> 
> it currently has `# pylint: disable=line-too-long`, you'll need to add `# pylint: disable=too-many-lines`. They're very similar 😆

yeah didn't notice 🤣🤣🤣

**Review by danaelhe — APPROVED** [review]
Great contribution!! Thank you so much 🚢

**Pull request merged**
