### PR TITLE
Add Mocked Tests: Volume Actions

### PR DESCRIPTION
**Pull request by shivam-Purohit**
refers issue #203

Add mocked tests for volume action.
Add tests for volume_actions.get, volume_actions.list, volume_actions.post, volume_actions.post_by_id

### CODE REVIEW

**Comment by shivam-Purohit** [comment]
@danaelhe am I on the right path?

**Review by work-mohit — COMMENTED** [review]
@shivam-Purohit Yupp doing great !

**Review by work-mohit — COMMENTED** [review]
LGTM !

**Review by danaelhe — APPROVED** [review]
Looks FANTASTIC! Will merge once a commit has been pushed to fix lint tests pass (see comment from above)!

**Comment by shivam-Purohit** [comment]
@danaelhe I pushed the changes. Is it okay now?

**Comment by work-mohit** [comment]
> @danaelhe I pushed the changes. Is it okay now? Also, can't we automate it with something like github precommit? It will be a lot easier.

I was thinking about the same.

**Comment by danaelhe** [comment]
> @danaelhe I pushed the changes. Is it okay now? Also, can't we automate it with something like github precommit? It will be a lot easier.

That's a great idea. I'll write up a github issue for it. Thanks!

**Review by danaelhe — APPROVED** [review]

**Pull request merged**
